public class Constants {
    
    /** Picklist vals: Invoice Status__c */
    public static final String INVOICE_STATUS_DRAFT = 'Draft';
    public static final String INVOICE_STATUS_CANCELLED = 'Cancelled';
    public static final String INVOICE_STATUS_ACTIVATED = 'Activated';

    /** Picklist vals: Invoice PDFSyncSetting__c */
    public static final String INVOICE_PDF_SETTING_DEACTIVATED = 'Deactivated';
    public static final String INVOICE_PDF_SETTING_DELETE = 'Delete';
    public static final String INVOICE_PDF_SETTING_SYNC = 'Sync';

}
